import { useEffect, useState } from "react"
import { useDispatch, useSelector } from "react-redux"
import BarChart from "../Components/Test/BarChart"

const TestResultContainer = () => {

    const dispatch = useDispatch()
    const preTest = useSelector(state => state.test.preTest)
    const [test, setTest] = useState({

    })

    useEffect(() => {
        setTest(preTest)
        console.log(test);
    }, [dispatch, preTest, test])

    return (
        <div className="test-result-container">
            <div className="container">
                <div className="sec1">

                </div>
                <div className="sec2">
                    <div id="test-info">
                        <p id="test-sel">
                            Binomial Test 
                        </p>
                        <p id="desc-test">
                        Used a Binomial Test to verify if there was a significant preference difference between images generated by the two models (p=0.05).
                        </p>
                    </div>
                    <div id="model-div">
                        <div id="model-1">
                            <img src="/images/orange.svg" alt="o" />
                            <div style={{
                                width: "1vw"
                            }}>
                            </div>
                            <p className="model-name">
                                {"~/" + test.file1}
                            </p>
                        </div>
                        <div id="model-2">
                            <img src="/images/soda.svg" alt="o" />
                            <div style={{
                                width: "1vw"
                            }}>

                            </div>
                            <p className="model-name">
                                {"~/" + test.file2}
                            </p>
                        </div>
                    </div>
                    <div id="test-type">
                        <p id="test-type-text">
                            Test type
                        </p>
                        <img src={`/images/${test.testSel}.svg`} alt="test-type" />
                    </div>
                    
                </div>
                <div className="sec3">
                    <div id="test-result">
                        
                        <BarChart per={50} sum={70}/>

                    </div>
                            

                </div>
            </div>
        </div>
    )
}


export default TestResultContainer
